#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI-1')

# DUAL MONITOR
# xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --secondary --mode 1920x1080 --rotate normal --left-of eDP-1
# bspc monitor eDP-1 -d I II III IV V 
# bspc monitor HDMI-1 -d VI VII VIII IX X

# SINGLE MONITOR
xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal 
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12
bspc config focused_border_color '#4cad98'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale ~/Desktop/wallpapers/mountain.jpg

setxkbmap es

polybar | picom 
